/* ============================================================
   TrekSense — data3.js
   65 more treks: Nepal, Kashmir, Sikkim & Darjeeling, plus
   deeper Himachal & Uttarakhand. Total catalogue: 120.
   Uses expandCompactTreks() + ensureTenOperators() from data2.js.
   ============================================================ */

const T3 = [
  /* ================= NEPAL (20) ================= */
  { id: "everest-base-camp", name: "Everest Base Camp", region: "Solukhumbu", state: "Nepal",
    diff: "Hard", scene: "glacier", ft: "18,514 ft", m: 5644, km: 130, days: 12,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 65000,
    lat: 27.69, lon: 86.73, base: "Lukla", wild: "alpine", tags: ["glacier"], fit: 4,
    desc: "The world's most famous walk — teahouse to teahouse up the Khumbu to the foot of <strong>Everest</strong>, capped by the Kala Patthar sunrise where the summit pyramid burns gold.",
    hl: ["Kala Patthar sunrise", "Namche Bazaar", "Tengboche monastery", "Sherpa heartland", "Teahouse comfort"],
    cps: [["Lukla", "9,383 ft", "The famous mountain airstrip.", ["Kongde Ri"]],
          ["Namche Bazaar", "11,286 ft", "Sherpa capital in a natural amphitheatre.", ["Everest first view", "Thamserku", "Kongde Ri"]],
          ["Tengboche", "12,687 ft", "Monastery with the classic panorama.", ["Everest", "Lhotse", "Ama Dablam"]],
          ["Dingboche", "14,470 ft", "Acclimatisation village of stone walls.", ["Ama Dablam", "Island Peak", "Lhotse wall"]],
          ["Lobuche", "16,210 ft", "Beside the Khumbu glacier moraine.", ["Nuptse", "Pumori"]],
          ["Everest Base Camp", "17,598 ft", "Icefall's edge — expedition city in spring.", ["Khumbu Icefall", "Nuptse", "Pumori"]],
          ["Kala Patthar", "18,514 ft", "THE Everest viewpoint.", ["Everest", "Nuptse", "Ama Dablam", "Pumori", "Changtse"]]],
    crux: ["Lobuche → Gorak Shep → Kala Patthar", "Two thin-air days at 50% oxygen where teahouse comfort stops compensating; most evacuations happen here from going too fast lower down."] },

  { id: "annapurna-base-camp", name: "Annapurna Base Camp", region: "Kaski", state: "Nepal",
    diff: "Moderate", scene: "valley", ft: "13,550 ft", m: 4130, km: 67, days: 7,
    season: "Mar - May, Sep - Dec", seasons: ["Spring", "Autumn", "Winter"], price: 32000,
    lat: 28.31, lon: 83.79, base: "Nayapul (Pokhara)", wild: "forest", tags: [], fit: 3,
    desc: "Into the <strong>Annapurna Sanctuary</strong> — a hidden glacial amphitheatre ringed by ten peaks over 6,000 m, reached through rhododendron forest and Gurung villages.",
    hl: ["360° sanctuary wall", "Machapuchare views", "Gurung villages", "Hot springs at Jhinu", "Teahouse trail"],
    cps: [["Nayapul", "3,540 ft", "Roadhead from Pokhara.", ["Foothill terraces"]],
          ["Chhomrong", "7,120 ft", "Gurung village gateway to the sanctuary.", ["Annapurna South", "Machapuchare"]],
          ["Deurali", "10,600 ft", "Gorge camp below the avalanche zones.", ["Machapuchare wall", "Hiunchuli"]],
          ["Machapuchare Base Camp", "12,140 ft", "The fishtail fills the sky.", ["Machapuchare", "Annapurna III", "Gangapurna"]],
          ["Annapurna Base Camp", "13,550 ft", "Inside the ring of giants.", ["Annapurna I", "Annapurna South", "Machapuchare", "Hiunchuli", "Gangapurna"]]],
    crux: ["The Deurali avalanche corridor", "In winter and early spring, slide paths cross the trail between Deurali and MBC — teams move early and singly through the chutes."] },

  { id: "annapurna-circuit", name: "Annapurna Circuit", region: "Manang-Mustang", state: "Nepal",
    diff: "Hard", scene: "alpine", ft: "17,769 ft", m: 5416, km: 160, days: 12,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 48000,
    lat: 28.23, lon: 84.37, base: "Besisahar", wild: "alpine", tags: ["snow"], fit: 4,
    desc: "The classic horseshoe around the Annapurna massif — subtropical valleys to the wind-scoured <strong>Thorong La at 5,416 m</strong>, finishing in the holy town of Muktinath.",
    hl: ["Thorong La crossing", "Manang valley", "Muktinath temple", "Climate-zone journey", "Teahouse classic"],
    cps: [["Besisahar", "2,500 ft", "Circuit start in the rice terraces.", ["Marsyangdi valley"]],
          ["Chame", "8,890 ft", "District HQ under Lamjung Himal.", ["Lamjung Himal", "Annapurna II"]],
          ["Manang", "11,545 ft", "Acclimatisation town — bakeries at 3,500 m.", ["Gangapurna", "Annapurna III", "Tilicho Peak"]],
          ["Thorong Phedi", "14,600 ft", "Foot of the pass.", ["Yakawa Kang"]],
          ["Thorong La", "17,769 ft", "Prayer-flag saddle — the high point.", ["Yakawa Kang", "Khatung Kang", "Dhaulagiri (far)"]],
          ["Muktinath", "12,170 ft", "108 spouts and an eternal flame.", ["Dhaulagiri", "Nilgiri (Nepal)"]]],
    crux: ["Thorong La before the wind", "A 3 AM start beats the violent mid-morning westerlies; late parties get turned back at the pass shoulder."] },

  { id: "ghorepani-poon-hill", name: "Ghorepani Poon Hill", region: "Kaski", state: "Nepal",
    diff: "Easy", scene: "sunset", ft: "10,525 ft", m: 3210, km: 32, days: 4,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Autumn"], price: 18000,
    lat: 28.4, lon: 83.69, base: "Nayapul (Pokhara)", wild: "forest", tags: ["light"], fit: 2,
    desc: "Nepal's best short trek — stone staircases through rhododendron forest to the <strong>Poon Hill sunrise</strong>, where Dhaulagiri and the Annapurnas line up like a mural.",
    hl: ["Poon Hill sunrise", "Rhododendron bloom (Mar-Apr)", "Magar villages", "Teahouse fireplaces", "First-Himalaya perfect"],
    cps: [["Nayapul", "3,540 ft", "Trailhead from Pokhara.", ["Modi Khola valley"]],
          ["Tikhedhunga", "5,180 ft", "Streamside stone village.", ["Terraced hills"]],
          ["Ghorepani", "9,430 ft", "Rhododendron ridge town.", ["Dhaulagiri", "Annapurna South"]],
          ["Poon Hill", "10,525 ft", "The famous sunrise tower.", ["Dhaulagiri", "Annapurna South", "Machapuchare", "Nilgiri (Nepal)", "Hiunchuli"]]],
    crux: ["Ulleri's 3,300 stone steps", "The infamous staircase out of Tikhedhunga — every guidebook warns you, every trekker still swears at it."] },

  { id: "mardi-himal", name: "Mardi Himal", region: "Kaski", state: "Nepal",
    diff: "Moderate", scene: "meadow", ft: "14,764 ft", m: 4500, km: 40, days: 5,
    season: "Mar - May, Oct - Dec", seasons: ["Spring", "Autumn", "Winter"], price: 24000,
    lat: 28.35, lon: 83.9, base: "Kande (Pokhara)", wild: "forest", tags: [], fit: 3,
    desc: "The ridge that sneaks you to within touching distance of <strong>Machapuchare</strong> — Nepal's newest classic, quiet forest camps below a knife-line walk to Base Camp viewpoint.",
    hl: ["Machapuchare up close", "Ridge-line trail", "Quieter than ABC", "Forest camps", "Short from Pokhara"],
    cps: [["Kande", "5,600 ft", "Roadhead above Phewa lake.", ["Pokhara valley"]],
          ["Forest Camp", "8,300 ft", "Deep rhododendron camp.", ["Glimpses only — patience"]],
          ["High Camp", "11,880 ft", "Above the cloud sea.", ["Machapuchare", "Annapurna South"]],
          ["Mardi Base Camp Viewpoint", "14,764 ft", "The fishtail at arm's length.", ["Machapuchare", "Annapurna South", "Hiunchuli", "Mardi Himal"]]],
    crux: ["High Camp → Viewpoint ridge", "A narrow, occasionally icy ridgeline with big drops either side — spectacular, but poles and calm feet required."] },

  { id: "langtang-valley", name: "Langtang Valley", region: "Rasuwa", state: "Nepal",
    diff: "Moderate", scene: "valley", ft: "15,655 ft", m: 4773, km: 65, days: 7,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 28000,
    lat: 28.16, lon: 85.31, base: "Syabrubesi", wild: "alpine", tags: [], fit: 3,
    desc: "The 'valley of glaciers' rebuilt after 2015 — Tamang villages, yak pastures and the climb to <strong>Kyanjin Ri</strong>, eye-to-eye with Langtang Lirung's hanging ice.",
    hl: ["Kyanjin Ri summit", "Langtang Lirung glaciers", "Tamang culture", "Rebuild-tourism that matters", "Close to Kathmandu"],
    cps: [["Syabrubesi", "4,850 ft", "Trailhead town on the Trisuli.", ["Gorge walls"]],
          ["Lama Hotel", "8,100 ft", "Forest lodges by the river.", ["Langtang river gorge"]],
          ["Langtang Village", "11,254 ft", "Rebuilt above the 2015 landslide.", ["Langtang Lirung"]],
          ["Kyanjin Gompa", "12,697 ft", "Monastery, bakery, cheese factory.", ["Langtang Lirung", "Ganja La"]],
          ["Kyanjin Ri", "15,655 ft", "The valley's grandstand.", ["Langtang Lirung", "Dorje Lakpa", "Ganesh Himal", "Yala Peak"]]],
    crux: ["Kyanjin Ri's deceptive cone", "3,000 ft above the bakery — most underestimate it after 'an easy valley walk' and summit gassed. Start pre-dawn."] },

  { id: "gokyo-lakes", name: "Gokyo Lakes & Gokyo Ri", region: "Solukhumbu", state: "Nepal",
    diff: "Hard", scene: "lakes", ft: "17,575 ft", m: 5357, km: 92, days: 11,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 55000,
    lat: 27.95, lon: 86.69, base: "Lukla", wild: "alpine", tags: ["glacier"], fit: 4,
    desc: "The connoisseur's Khumbu — six turquoise lakes beside Nepal's longest glacier, and from <strong>Gokyo Ri</strong> a view of <strong>four 8,000ers at once</strong>.",
    hl: ["Four 8,000m peaks in one view", "Turquoise sacred lakes", "Ngozumpa glacier", "Quieter than EBC", "Cho La add-on"],
    cps: [["Lukla", "9,383 ft", "Khumbu airstrip.", ["Kongde Ri"]],
          ["Namche Bazaar", "11,286 ft", "The Sherpa hub.", ["Thamserku", "Kongde"]],
          ["Dole", "13,451 ft", "Yak pastures up the quiet fork.", ["Cho Oyu ahead"]],
          ["Machhermo", "14,468 ft", "Last village before the lakes.", ["Kangtega", "Thamserku"]],
          ["Gokyo", "15,580 ft", "Lodge village on lake three.", ["Cho Oyu", "Gokyo lakes"]],
          ["Gokyo Ri", "17,575 ft", "The four-giant panorama.", ["Everest", "Lhotse", "Makalu", "Cho Oyu", "Ngozumpa glacier"]]],
    crux: ["Gokyo Ri at dawn", "1,900 ft of switchbacks on 53% oxygen for the sunrise — slow is the only speed that summits."] },

  { id: "everest-three-passes", name: "Everest Three Passes", region: "Solukhumbu", state: "Nepal",
    diff: "Expedition", scene: "glacier", ft: "18,159 ft", m: 5535, km: 160, days: 18,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 85000,
    lat: 27.69, lon: 86.73, base: "Lukla", wild: "glacier", tags: ["glacier", "snow"], fit: 5,
    desc: "The complete Khumbu — <strong>Kongma La, Cho La and Renjo La</strong> chained into one grand circuit with EBC, Kala Patthar and Gokyo Ri en route. The hardest teahouse trek there is.",
    hl: ["Three 5,300m+ passes", "EBC + Gokyo combined", "Glacier crossings", "18-day endurance", "Khumbu grand slam"],
    cps: [["Lukla", "9,383 ft", "Round-trip start and finish.", ["Kongde Ri"]],
          ["Chhukung", "15,518 ft", "Under the Lhotse wall.", ["Lhotse", "Island Peak", "Ama Dablam"]],
          ["Kongma La", "18,159 ft", "Highest and hardest of the three.", ["Makalu", "Lhotse", "Pokalde"]],
          ["Cho La", "17,782 ft", "The icy one — crampons help.", ["Ama Dablam", "Cholatse"]],
          ["Renjo La", "17,560 ft", "The view one — Everest over Gokyo's lakes.", ["Everest", "Lhotse", "Makalu", "Gokyo lakes below"]]],
    crux: ["Cho La's glacier shelf", "A slick ice shelf guarded by boulder scrambles on both sides; in wind or fresh snow parties rope together or wait it out."] },

  { id: "manaslu-circuit", name: "Manaslu Circuit", region: "Gorkha", state: "Nepal",
    diff: "Hard", scene: "alpine", ft: "16,752 ft", m: 5106, km: 177, days: 14,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 62000,
    lat: 28.28, lon: 84.9, base: "Machha Khola", wild: "alpine", tags: ["snow"], fit: 4,
    desc: "What the Annapurna Circuit was 30 years ago — a restricted-permit loop around the world's eighth-highest mountain, over the snow saddle of <strong>Larkya La</strong>.",
    hl: ["Larkya La crossing", "Restricted-area quiet", "Tibetan villages", "Manaslu's twin summit", "Budhi Gandaki gorges"],
    cps: [["Machha Khola", "2,870 ft", "Gorge-mouth trailhead.", ["Budhi Gandaki gorge"]],
          ["Jagat", "4,460 ft", "Flagstone permit village.", ["Sringi Himal glimpse"]],
          ["Samagaon", "11,580 ft", "Tibetan village below the mountain.", ["Manaslu", "Pungyen glacier"]],
          ["Dharamsala", "14,760 ft", "Bleak pass-foot camp.", ["Larkya Peak"]],
          ["Larkya La", "16,752 ft", "The long snow saddle.", ["Himlung", "Cheo Himal", "Annapurna II (far)"]],
          ["Bimthang", "12,205 ft", "Meadow bowl on the far side.", ["Manaslu west face"]]],
    crux: ["Larkya La's endless top", "The 'pass' is a 3 km high plateau — in wind or whiteout its length, not its height, is what exhausts teams."] },

  { id: "upper-mustang", name: "Upper Mustang", region: "Mustang", state: "Nepal",
    diff: "Moderate", scene: "forest", ft: "13,681 ft", m: 4170, km: 120, days: 12,
    season: "May - Oct (rain-shadow)", seasons: ["Summer", "Monsoon", "Autumn"], price: 78000,
    lat: 28.78, lon: 83.72, base: "Jomsom", wild: "spiti", tags: [], fit: 3,
    desc: "The <strong>walled kingdom of Lo</strong> — a Tibetan desert of red cliffs, cave monasteries and the medieval capital Lo Manthang, trekable even in monsoon thanks to the rain shadow.",
    hl: ["Lo Manthang walled city", "Sky caves & gompas", "Monsoon-proof desert", "Restricted-permit mystique", "Tiji festival (May)"],
    cps: [["Jomsom", "8,976 ft", "Windy airstrip on the Kali Gandaki.", ["Nilgiri (Nepal)", "Dhaulagiri"]],
          ["Chele", "10,138 ft", "First village of Upper Mustang proper.", ["Kali Gandaki canyons"]],
          ["Ghami", "11,660 ft", "Longest mani wall in Nepal.", ["Red cliff amphitheatres"]],
          ["Nyi La", "13,681 ft", "High pass of the route.", ["Annapurna (far)", "Damodar ranges"]],
          ["Lo Manthang", "12,600 ft", "The walled capital of Lo.", ["Damodar Himal", "Tibet border ranges"]]],
    crux: ["Wind, not altitude", "The Kali Gandaki's afternoon gales sandblast the trail daily from 11 AM — Mustang days start and end early."] },

  { id: "khopra-ridge", name: "Khopra Ridge & Khayer Lake", region: "Myagdi", state: "Nepal",
    diff: "Moderate", scene: "meadow", ft: "15,092 ft", m: 4600, km: 50, days: 7,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 30000,
    lat: 28.4, lon: 83.69, base: "Nayapul (Pokhara)", wild: "meadow", tags: [], fit: 3,
    desc: "The community-lodge alternative to Poon Hill — a lonely ridge staring into <strong>Dhaulagiri's east face</strong>, with a sacred-lake day hike at 4,600 m.",
    hl: ["Dhaulagiri face views", "Community lodges", "Khayer Lake pilgrimage", "Crowd-free ridge", "Combines with Poon Hill"],
    cps: [["Nayapul", "3,540 ft", "Common Annapurna trailhead.", ["Foothills"]],
          ["Swanta", "7,380 ft", "Farming village off the main trail.", ["Dhaulagiri glimpse"]],
          ["Khopra Ridge", "11,975 ft", "Lodge on the very crest.", ["Dhaulagiri", "Annapurna South", "Nilgiri (Nepal)"]],
          ["Khayer Lake", "15,092 ft", "Sacred tarn below Annapurna South.", ["Annapurna South", "Fang", "Khayer Barah shrine"]]],
    crux: ["Khayer Lake day: 6,000 ft round trip", "A huge single-day out-and-back gain along an exposed ridge — start at 4 AM and turn around at any weather doubt."] },

  { id: "island-peak", name: "Island Peak (Imja Tse)", region: "Solukhumbu", state: "Nepal",
    diff: "Expedition", scene: "glacier", ft: "20,305 ft", m: 6189, km: 140, days: 16,
    season: "Apr - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 145000,
    lat: 27.92, lon: 86.94, base: "Lukla (via Chhukung)", wild: "glacier", tags: ["rope", "glacier"], fit: 5,
    desc: "Nepal's most-climbed 6,000er — ladders over crevasses, fixed lines up the headwall, and a summit ridge <strong>under the immense Lhotse south face</strong>. The classic first Himalayan climbing peak.",
    hl: ["First 6,000er classic", "Ladder crevasse crossings", "Lhotse wall backdrop", "EBC acclimatisation route", "Full climbing course en route"],
    cps: [["Lukla", "9,383 ft", "Fly-in trailhead.", ["Kongde"]],
          ["Chhukung", "15,518 ft", "Climbing base village.", ["Lhotse", "Ama Dablam"]],
          ["Island Peak Base Camp", "16,690 ft", "Below the moraine ramp.", ["Imja lake", "Baruntse"]],
          ["Crampon Point", "18,700 ft", "Rock ends, glacier begins.", ["Lhotse south face"]],
          ["Island Peak Summit", "20,305 ft", "Ridge between the giants.", ["Lhotse", "Makalu", "Ama Dablam", "Baruntse"]]],
    crux: ["The headwall at 19,800 ft", "300 m of 45–55° fixed line to the summit ridge, often queued — jumar efficiency decides whether you summit before the sun softens the snow."] },

  { id: "mera-peak", name: "Mera Peak", region: "Solukhumbu", state: "Nepal",
    diff: "Expedition", scene: "glacier", ft: "21,247 ft", m: 6476, km: 110, days: 15,
    season: "Apr - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 155000,
    lat: 27.71, lon: 86.87, base: "Lukla (via Zatrwa La)", wild: "glacier", tags: ["rope", "glacier"], fit: 5,
    desc: "Nepal's highest trekking peak — a long glacier plod to a summit that shows <strong>five 8,000ers in one sweep</strong>: Everest, Lhotse, Makalu, Cho Oyu and Kanchenjunga.",
    hl: ["Highest trekking peak", "Five 8,000ers from summit", "Remote Hinku valley", "Big glacier travel", "True high-altitude test"],
    cps: [["Lukla", "9,383 ft", "Cross the Zatrwa La out of the Khumbu.", ["Kongde"]],
          ["Kothe", "11,975 ft", "Hinku forest camp.", ["Mera first view"]],
          ["Khare", "16,486 ft", "Climbing base with gear checks.", ["Mera glacier"]],
          ["Mera High Camp", "19,029 ft", "Perched on the glacier shelf.", ["Everest", "Makalu", "Chamlang"]],
          ["Mera Summit", "21,247 ft", "The five-giant horizon.", ["Everest", "Lhotse", "Makalu", "Cho Oyu", "Kanchenjunga"]]],
    crux: ["Summit night from High Camp", "6–8 hours of relentless 30° snow at 45% oxygen; technically simple, physiologically brutal — the highest non-technical summit most people will ever attempt."] },

  { id: "lobuche-east", name: "Lobuche East", region: "Solukhumbu", state: "Nepal",
    diff: "Expedition", scene: "glacier", ft: "20,075 ft", m: 6119, km: 130, days: 15,
    season: "Apr - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 150000,
    lat: 27.96, lon: 86.79, base: "Lukla (via Lobuche)", wild: "glacier", tags: ["rope", "glacier"], fit: 5,
    desc: "The connoisseur's Khumbu summit — steeper and quieter than Island Peak, with a ridge finale that stares <strong>straight at Everest across the valley</strong>.",
    hl: ["Everest head-on from summit", "Steeper than Island Peak", "Combines with EBC", "Mixed rock-and-ice", "Small-team feel"],
    cps: [["Lukla", "9,383 ft", "Khumbu fly-in.", ["Kongde"]],
          ["Lobuche", "16,210 ft", "Teahouse base by the moraine.", ["Nuptse", "Pumori"]],
          ["Lobuche High Camp", "17,700 ft", "Rock slabs camp.", ["Ama Dablam", "Cholatse"]],
          ["Lobuche East Summit", "20,075 ft", "Ridge with the Everest mural.", ["Everest", "Nuptse", "Lhotse", "Ama Dablam", "Pumori"]]],
    crux: ["The slab band to the ridge", "Fixed lines over smooth 40° granite slabs before the snow ridge — awkward in crampons and the reason this counts as a step up from Island Peak."] },

  { id: "pikey-peak", name: "Pikey Peak", region: "Solukhumbu", state: "Nepal",
    diff: "Easy", scene: "sunset", ft: "13,336 ft", m: 4065, km: 40, days: 5,
    season: "Mar - May, Oct - Dec", seasons: ["Spring", "Autumn", "Winter"], price: 22000,
    lat: 27.58, lon: 86.55, base: "Dhap (Lower Solu)", wild: "forest", tags: ["light"], fit: 2,
    desc: "Hillary called this <strong>his favourite Everest view</strong> — a gentle Sherpa-country ridge with monasteries, yak cheese and a sunrise that runs from Dhaulagiri to Kanchenjunga.",
    hl: ["Hillary's favourite view", "No flights needed", "Sherpa villages & gompas", "Winter-friendly", "Everest to Kanchenjunga sweep"],
    cps: [["Dhap", "9,350 ft", "Roadhead from Kathmandu.", ["Solu ridges"]],
          ["Jhapre", "9,180 ft", "Village with a postcard stupa.", ["Everest glimpse", "Numbur"]],
          ["Pikey Base Camp", "11,975 ft", "Lodge below the double summit.", ["Numbur", "Thamserku"]],
          ["Pikey Peak", "13,336 ft", "The 360° Solu grandstand.", ["Everest", "Numbur", "Thamserku", "Kanchenjunga (far)", "Dhaulagiri (far)"]]],
    crux: ["Cold, not climb", "Nothing here is hard — but the summit sunrise wind at −10 °C sends unprepared trekkers down before the show starts. Bring the down jacket."] },

  { id: "gosainkunda", name: "Langtang Gosainkunda", region: "Rasuwa", state: "Nepal",
    diff: "Moderate", scene: "lakes", ft: "15,121 ft", m: 4610, km: 75, days: 8,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 30000,
    lat: 28.08, lon: 85.41, base: "Dhunche", wild: "alpine", tags: ["pilgrim"], fit: 3,
    desc: "Shiva's trident struck this mountainside and <strong>108 lakes</strong> appeared — cross the Lauribina La past the holiest of them, mirror-black Gosainkunda.",
    hl: ["Sacred 108-lake plateau", "Lauribina La crossing", "Janai Purnima pilgrimage", "Links Langtang & Helambu", "Frozen-lake winters"],
    cps: [["Dhunche", "6,450 ft", "Rasuwa district HQ.", ["Trisuli valley"]],
          ["Sing Gompa", "10,840 ft", "Monastery and yak-cheese factory.", ["Langtang Lirung"]],
          ["Gosainkunda", "14,370 ft", "The sacred lake itself.", ["Langtang range mirrored"]],
          ["Lauribina La", "15,121 ft", "Pass above the lake chain.", ["Ganesh Himal", "Manaslu (far)", "lake chain below"]]],
    crux: ["Lauribina's iced steps", "The stone path above the lakes holds black ice most mornings outside high summer — microspikes turn danger into stroll."] },

  { id: "helambu", name: "Helambu Circuit", region: "Sindhupalchok", state: "Nepal",
    diff: "Easy", scene: "forest", ft: "11,975 ft", m: 3650, km: 45, days: 5,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Autumn"], price: 20000,
    lat: 27.9, lon: 85.5, base: "Sundarijal (Kathmandu)", wild: "forest", tags: ["light"], fit: 2,
    desc: "Kathmandu's backyard trek — Sherpa and Tamang villages, terraced hills and monastery ridges, <strong>starting from the city's edge</strong> with no flights or long drives.",
    hl: ["Starts at Kathmandu's edge", "Hyolmo culture", "Monastery ridges", "Year-round & low", "Gentle teahouse loop"],
    cps: [["Sundarijal", "4,600 ft", "Water-pipe staircase out of the city.", ["Kathmandu valley rim"]],
          ["Chisapani", "7,050 ft", "Ridge town with big-range dawn.", ["Langtang range", "Jugal Himal"]],
          ["Kutumsang", "8,070 ft", "Tamang saddle village.", ["Terraced ridges"]],
          ["Tharepati", "11,975 ft", "High point of the loop.", ["Jugal Himal", "Dorje Lakpa", "Langtang range"]]],
    crux: ["Navigation over effort", "Trails braid through farmland and forest with sparse marking — the only day people struggle is when they refuse to ask a villager."] },

  { id: "tsum-valley", name: "Tsum Valley", region: "Gorkha", state: "Nepal",
    diff: "Moderate", scene: "valley", ft: "12,300 ft", m: 3750, km: 90, days: 11,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 55000,
    lat: 28.4, lon: 85.06, base: "Machha Khola", wild: "alpine", tags: ["pilgrim"], fit: 3,
    desc: "The <strong>hidden valley of happiness</strong> — a restricted Tibetan-Buddhist sanctum off the Manaslu trail where hunting has been banned for centuries and gompas outnumber lodges.",
    hl: ["Sacred no-kill valley", "Mu Gompa at the head", "Milarepa's cave", "Restricted-permit quiet", "Living Tibetan culture"],
    cps: [["Machha Khola", "2,870 ft", "Shared start with Manaslu.", ["Budhi Gandaki gorge"]],
          ["Chumling", "7,710 ft", "First Tsum village — the world changes.", ["Ganesh Himal"]],
          ["Nile", "11,090 ft", "Upper valley twin villages.", ["Sringi Himal"]],
          ["Mu Gompa", "12,300 ft", "Monastery at the valley's end.", ["Ganesh Himal", "Sringi Himal", "Tibet border hills"]]],
    crux: ["Long gorge days in and out", "The Budhi Gandaki approach is the price of admission — three gorge days each way frame the sanctuary."] },

  { id: "rara-lake", name: "Rara Lake", region: "Mugu", state: "Nepal",
    diff: "Easy", scene: "lakes", ft: "9,810 ft", m: 2990, km: 35, days: 5,
    season: "Apr - Jun, Sep - Nov", seasons: ["Spring", "Summer", "Autumn"], price: 45000,
    lat: 29.53, lon: 82.09, base: "Talcha (Mugu)", wild: "forest", tags: ["light"], fit: 2,
    desc: "Nepal's biggest lake, hidden in its remotest west — <strong>a sapphire in pine forest</strong> that changes colour by the hour, in a national park most Nepalis haven't seen.",
    hl: ["Nepal's largest lake", "Far-west wilderness", "Pine & juniper forests", "Boat & horse options", "True off-map feel"],
    cps: [["Talcha Airstrip", "9,000 ft", "Fly-in from Nepalgunj.", ["Mugu hills"]],
          ["Rara Lake", "9,810 ft", "The sapphire itself.", ["Chuchemara ridge", "Kanjiroba (far)"]],
          ["Murma Top", "11,320 ft", "Viewpoint over the whole lake.", ["Rara panorama", "Api-Saipal (far)"]]],
    crux: ["Getting there at all", "The trek is gentle; the two flights (or three-day drive) are the adventure. Build buffer days for Nepalgunj weather."] },

  { id: "kanchenjunga-base-camp", name: "Kanchenjunga North BC", region: "Taplejung", state: "Nepal",
    diff: "Hard", scene: "glacier", ft: "16,900 ft", m: 5150, km: 140, days: 18,
    season: "Apr - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 95000,
    lat: 27.35, lon: 87.67, base: "Taplejung", wild: "alpine", tags: [], fit: 5,
    desc: "To <strong>Pangpema</strong>, beneath the north face of the world's third-highest mountain — Nepal's wildest teahouse trek, three weeks where villages still outnumber trekkers.",
    hl: ["Pangpema north face view", "Nepal's remotest classic", "Rai & Limbu villages", "Jannu's fortress wall", "Three-week commitment"],
    cps: [["Taplejung", "5,900 ft", "Hill bazaar trailhead.", ["Tamor valley"]],
          ["Ghunsa", "11,270 ft", "Tibetan village and rest hub.", ["Jannu glimpse"]],
          ["Lhonak", "15,570 ft", "Bleak upper-valley camp.", ["Wedge Peak", "Mera (Kangchenjunga)"]],
          ["Pangpema (North BC)", "16,900 ft", "The north-face amphitheatre.", ["Kanchenjunga", "Jannu", "Wedge Peak", "Nepal Peak"]]],
    crux: ["Landslide traverses past Ghunsa", "Several cliff-cut sections cross active slide zones — teams time them for early morning and never linger."] },

  /* ================= KASHMIR (8) ================= */
  { id: "tarsar-marsar", name: "Tarsar Marsar", region: "Anantnag", state: "Jammu & Kashmir",
    diff: "Moderate", scene: "lakes", ft: "13,500 ft", m: 4115, km: 48, days: 7,
    season: "Jul - Sep", seasons: ["Monsoon", "Summer"], price: 14500,
    lat: 34.09, lon: 75.28, base: "Aru (Pahalgam)", wild: "meadow", tags: [], fit: 3,
    desc: "KGL's dreamier sibling — <strong>twin almond-shaped lakes</strong> you camp beside rather than march past, in meadows that Kashmiri shepherds still own.",
    hl: ["Camp ON the lakeshores", "Twin alpine lakes", "Gentler than KGL", "Aru valley start", "Shepherd meadows"],
    cps: [["Aru", "7,920 ft", "Meadow village above Pahalgam.", ["Lidder valley"]],
          ["Lidderwat", "9,022 ft", "Riverside camping classic.", ["Kolahoi glimpse"]],
          ["Shekwas", "11,039 ft", "Rolling meadow bowl.", ["Kolahoi"]],
          ["Tarsar Lake", "12,449 ft", "First of the twins.", ["Kolahoi", "Tarsar ridge"]],
          ["Tarsar Pass", "13,500 ft", "Ridge between the twins.", ["Tarsar & Marsar both below", "Kolahoi"]],
          ["Sundersar", "12,946 ft", "Third hidden lake camp.", ["Marsar overlook ridge"]]],
    crux: ["The Marsar weather window", "Marsar hides in a cloud-trap bowl — most see it before 7 AM or not at all. Camp at Sundersar and go at dawn."] },

  { id: "kolahoi-base-camp", name: "Kolahoi Base Camp", region: "Anantnag", state: "Jammu & Kashmir",
    diff: "Moderate", scene: "glacier", ft: "11,808 ft", m: 3600, km: 30, days: 4,
    season: "Jun - Sep", seasons: ["Summer", "Monsoon"], price: 9500,
    lat: 34.14, lon: 75.26, base: "Aru (Pahalgam)", wild: "meadow", tags: [], fit: 3,
    desc: "To the foot of <strong>'Kashmir's Matterhorn'</strong> — Kolahoi's pyramid rises 2,000 m above a dying glacier at the head of the Lidder valley.",
    hl: ["Kolahoi's rock pyramid", "Lidder valley meadows", "Short & scenic", "Gujjar shepherd camps", "Combines with Tarsar"],
    cps: [["Aru", "7,920 ft", "Trailhead meadow village.", ["Lidder valley"]],
          ["Lidderwat", "9,022 ft", "The great camping meadow.", ["Valley bend pines"]],
          ["Kolahoi Base Camp", "11,808 ft", "Moraine meadow below the face.", ["Kolahoi (Gwash Brari)", "Kolahoi glacier"]]],
    crux: ["Moraine line to the glacier snout", "The last hour crosses live moraine with rockfall runnels — helmet-zone respect even on a 'short easy trek'."] },

  { id: "naranag-gangbal", name: "Naranag – Gangbal Lakes", region: "Ganderbal", state: "Jammu & Kashmir",
    diff: "Moderate", scene: "lakes", ft: "13,124 ft", m: 4001, km: 30, days: 4,
    season: "Jun - Sep", seasons: ["Summer", "Monsoon"], price: 11500,
    lat: 34.35, lon: 74.95, base: "Naranag", wild: "alpine", tags: ["pilgrim"], fit: 3,
    desc: "The express route to <strong>KGL's grand finale</strong> — straight up from the ancient Naranag temples to Mt. Harmukh's twin lakes, trout rings widening at dusk.",
    hl: ["Gangbal & Nundkol lakes", "Mt. Harmukh's glacier", "8th-century temples", "Weekend-length KGL taste", "Trout-fishing option"],
    cps: [["Naranag", "7,450 ft", "Stone temple complex trailhead.", ["Wangath valley"]],
          ["Trunkhol", "11,155 ft", "Meadow camp under Harmukh.", ["Harmukh"]],
          ["Butsheri Top", "13,124 ft", "Ridge viewpoint.", ["Harmukh", "both lakes below"]],
          ["Gangbal Lake", "11,975 ft", "The great lake beneath the peak.", ["Harmukh & its glacier"]]],
    crux: ["The relentless Naranag staircase", "4,000 ft gain on day one, much of it stone steps through pine — the toll booth for a very short approach."] },

  { id: "warwan-valley", name: "Warwan Valley Traverse", region: "Kishtwar-Anantnag", state: "Jammu & Kashmir",
    diff: "Hard", scene: "valley", ft: "13,810 ft", m: 4210, km: 120, days: 9,
    season: "Jul - Sep", seasons: ["Monsoon", "Summer"], price: 24500,
    lat: 33.9, lon: 75.4, base: "Panikhar (Suru) / Inshan", wild: "alpine", tags: [], fit: 4,
    desc: "The valley time forgot — a nine-day crossing from Suru's moonscape into <strong>Warwan's untouched green</strong>, over glacier snouts and meadows without a single roadhead between.",
    hl: ["True wilderness traverse", "Kaintal glacier crossing", "Villages without roads", "Ladakh-to-Kashmir contrast", "Committed nine days"],
    cps: [["Panikhar", "10,760 ft", "Suru valley start (Ladakh side).", ["Nun-Kun massif"]],
          ["Kaintal Base", "12,470 ft", "Below the glacier crossing.", ["Kaintal icefall"]],
          ["Lomvilad Gali", "13,810 ft", "The pass into Warwan.", ["Nun-Kun behind", "Warwan green ahead"]],
          ["Sukhnai", "8,850 ft", "First Warwan village — another century.", ["Warwan valley walls"]],
          ["Inshan", "8,200 ft", "Roadhead at last.", ["Marwah valley"]]],
    crux: ["The Kaintal glacier day", "A crevassed snout crossing with icy melt-streams — ropes out in early July, boulder-hopping misery by September. No bail-outs mid-route."] },

  { id: "doodhpathri-tosamaidan", name: "Doodhpathri – Tosamaidan", region: "Budgam", state: "Jammu & Kashmir",
    diff: "Easy", scene: "meadow", ft: "10,170 ft", m: 3100, km: 28, days: 4,
    season: "May - Sep", seasons: ["Summer", "Monsoon"], price: 8500,
    lat: 33.87, lon: 74.56, base: "Doodhpathri", wild: "meadow", tags: ["light"], fit: 2,
    desc: "Kashmir's <strong>'valley of milk'</strong> linked to Tosamaidan's mega-meadow — a gentle shepherd-trail walk through the Pir Panjal's greenest carpet, minus every crowd.",
    hl: ["Vast Pir Panjal meadows", "Gujjar & Bakarwal life", "Streams like spilt milk", "Family friendly", "Almost zero trekkers"],
    cps: [["Doodhpathri", "8,860 ft", "Meadow roadhead.", ["Pir Panjal slopes"]],
          ["Palmaidan", "9,500 ft", "Shepherd hut plateau.", ["Rolling meadow seas"]],
          ["Tosamaidan", "10,170 ft", "One of Asia's largest margs.", ["Pir Panjal crest", "Sunset Peak (far)"]]],
    crux: ["Way-finding in the green", "The meadows are so broad the 'trail' vanishes — a local guide is less for safety than for simply not circling."] },

  { id: "kounsarnag", name: "Aharbal – Kounsarnag", region: "Kulgam", state: "Jammu & Kashmir",
    diff: "Moderate", scene: "lakes", ft: "13,124 ft", m: 4000, km: 34, days: 4,
    season: "Jun - Sep", seasons: ["Summer", "Monsoon"], price: 9500,
    lat: 33.65, lon: 74.77, base: "Aharbal Falls", wild: "alpine", tags: ["pilgrim"], fit: 3,
    desc: "From the 'Niagara of Kashmir' to <strong>Kounsarnag</strong> — a 3 km-long glacial lake shaped like a footprint, locked in the high Pir Panjal and still wonderfully unknown.",
    hl: ["3 km glacial lake", "Aharbal waterfall start", "High Pir Panjal country", "Pilgrimage heritage", "Deep quiet"],
    cps: [["Aharbal", "7,920 ft", "The waterfall trailhead.", ["Veshaw gorge"]],
          ["Kungwattan", "9,840 ft", "Forest-edge meadow camp.", ["Pir Panjal ridges"]],
          ["Mahinag", "11,480 ft", "Spring camp below the lake shelf.", ["Craggy cirque walls"]],
          ["Kounsarnag", "13,124 ft", "The footprint lake.", ["Pir Panjal crest", "lake's own icebergs"]]],
    crux: ["Boulder shelf to the lake", "The final approach hops big talus where the path dissolves; ankles and attention required."] },

  { id: "sonamarg-vishansar", name: "Sonamarg – Vishansar Weekend", region: "Ganderbal", state: "Jammu & Kashmir",
    diff: "Moderate", scene: "lakes", ft: "12,139 ft", m: 3700, km: 28, days: 4,
    season: "Jul - Sep", seasons: ["Monsoon", "Summer"], price: 9950,
    lat: 34.36, lon: 75.29, base: "Shitkadi (Sonamarg)", wild: "meadow", tags: [], fit: 3,
    desc: "The first — many say best — chapter of the Great Lakes as a stand-alone: Nichnai's wildflower pass to <strong>Vishansar and Kishansar</strong>, then back before your leave runs out.",
    hl: ["Two great lakes in four days", "Nichnai Pass flowers", "KGL taster", "Trout-ring evenings", "Short-leave friendly"],
    cps: [["Shitkadi", "7,800 ft", "Sonamarg trailhead.", ["Thajiwas ridge"]],
          ["Nichnai", "11,500 ft", "Valley camp between rock walls.", ["Nichnai Pass"]],
          ["Vishansar Lake", "12,139 ft", "The first great lake.", ["Kishansar peak", "twin lake ridge"]]],
    crux: ["Nichnai Pass in rain", "The one climb of the route turns to peanut-butter mud in monsoon bursts — gaiters and humour required."] },

  { id: "bodpathri-lakes", name: "Bodpathri Lakes", region: "Budgam-Poonch", state: "Jammu & Kashmir",
    diff: "Moderate", scene: "lakes", ft: "13,000 ft", m: 3962, km: 36, days: 5,
    season: "Jul - Sep", seasons: ["Monsoon", "Summer"], price: 12500,
    lat: 33.8, lon: 74.5, base: "Yusmarg", wild: "meadow", tags: [], fit: 3,
    desc: "The Pir Panjal's secret lake district — tarns under <strong>Sunset Peak and Tatakooti</strong>, reached across meadows where Mughal emperors once rode to Kashmir.",
    hl: ["Pir Panjal lake chain", "Mughal-road history", "Sunset Peak views", "Yusmarg start", "Zero commercial crowds"],
    cps: [["Yusmarg", "7,870 ft", "Meadow resort trailhead.", ["Pir Panjal wall"]],
          ["Sang-e-Safed", "11,150 ft", "'White stone' valley camp.", ["Tatakooti"]],
          ["Bodpathri Lakes", "13,000 ft", "Tarn shelf under the crest.", ["Sunset Peak", "Tatakooti", "Mughal-pass ridgeline"]]],
    crux: ["Weather off the Pir Panjal crest", "Storms build on the Poonch side unseen and pour over the ridge fast — camps pitch storm-ready by 2 PM."] },

  /* ============ SIKKIM & DARJEELING (7) ============ */
  { id: "sandakphu-phalut", name: "Sandakphu – Phalut", region: "Darjeeling (Singalila)", state: "West Bengal",
    diff: "Moderate", scene: "sunset", ft: "11,930 ft", m: 3636, km: 47, days: 6,
    season: "Oct - Apr", seasons: ["Autumn", "Winter", "Spring"], price: 12500,
    lat: 27.11, lon: 88.0, base: "Manebhanjan", wild: "forest", tags: ["snow"], fit: 3,
    desc: "The <strong>Sleeping Buddha trek</strong> — walk the India–Nepal border ridge to the only place on Earth that lines up four of the five highest mountains in one horizon.",
    hl: ["Everest + Kanchenjunga together", "Sleeping Buddha skyline", "Teahouse ridge walk", "Land Rovers of 1950s", "Rhododendrons in April"],
    cps: [["Manebhanjan", "6,325 ft", "Land Rover-lined trailhead.", ["Singalila foothills"]],
          ["Tumling", "9,600 ft", "First ridge village (in Nepal!).", ["Kanchenjunga family"]],
          ["Sandakphu", "11,930 ft", "Bengal's highest point.", ["Everest", "Lhotse", "Makalu", "Kanchenjunga", "Chomolhari (far)"]],
          ["Phalut", "11,811 ft", "Quieter second summit of the ridge.", ["Kanchenjunga huge", "Everest cluster"]]],
    crux: ["Winter wind-chill on the ridge", "The trail is honest; the January ridge wind at −15 °C windchill is not. Layers make or break the sunrise."] },

  { id: "dzongri-trail", name: "Dzongri Trail (Short Goechala)", region: "West Sikkim", state: "Sikkim",
    diff: "Moderate", scene: "alpine", ft: "13,120 ft", m: 4000, km: 42, days: 6,
    season: "Mar - May, Oct - Dec", seasons: ["Spring", "Autumn", "Winter"], price: 15500,
    lat: 27.37, lon: 88.22, base: "Yuksom", wild: "forest", tags: [], fit: 3,
    desc: "Goechala's greatest hits in six days — the rhododendron climb to <strong>Dzongri Top's sunrise</strong>, where Kanchenjunga's entire court assembles, without the long valley slog beyond.",
    hl: ["Dzongri Top sunrise", "Kanchenjunga court view", "Rhododendron forests (Apr)", "Six-day Sikkim classic", "Yak-herder plateau"],
    cps: [["Yuksom", "5,670 ft", "First capital of Sikkim.", ["Forested hills"]],
          ["Tshoka", "9,700 ft", "Monastery hamlet in cloud forest.", ["Pandim glimpse"]],
          ["Dzongri", "12,980 ft", "The high yak plateau.", ["Kanchenjunga", "Kabru"]],
          ["Dzongri Top", "13,120 ft", "Prayer-flag sunrise point.", ["Kanchenjunga", "Kabru N & S", "Pandim", "Rathong", "Koktang"]]],
    crux: ["Tshoka → Dzongri in one pull", "3,300 ft through rhododendron with zero flat — the day that decides whether the plateau feels like heaven or hospital."] },

  { id: "green-lake", name: "Green Lake (Zemu Glacier)", region: "North Sikkim", state: "Sikkim",
    diff: "Hard", scene: "glacier", ft: "16,000 ft", m: 4877, km: 90, days: 12,
    season: "Apr - May, Oct", seasons: ["Spring", "Autumn"], price: 65000,
    lat: 27.73, lon: 88.6, base: "Lachen", wild: "glacier", tags: [], fit: 5,
    desc: "Sikkim's forbidden classic — up the Zemu glacier to Green Lake, beneath <strong>Kanchenjunga's colossal north-east face</strong> and Siniolchu, 'the most beautiful mountain in the world'.",
    hl: ["Kanchenjunga NE face", "Siniolchu views", "Rarely granted permits", "Zemu glacier wilderness", "Expedition-style camping"],
    cps: [["Lachen", "8,840 ft", "North Sikkim permit village.", ["Teesta gorge"]],
          ["Jakthang", "10,830 ft", "Forest camp in the Zemu valley.", ["Zemu river"]],
          ["Yabuk", "13,120 ft", "Above the treeline moraine.", ["Siniolchu"]],
          ["Green Lake", "16,000 ft", "The old mountaineers' base.", ["Kanchenjunga NE face", "Siniolchu", "Simvo", "Nepal Peak"]]],
    crux: ["Permits, then rockfall alleys", "Months of paperwork gets you in; the Yabuk cliff traverses above the Zemu keep you alert once you're there."] },

  { id: "barsey-rhododendron", name: "Barsey Rhododendron Trek", region: "West Sikkim", state: "Sikkim",
    diff: "Easy", scene: "forest", ft: "10,000 ft", m: 3048, km: 20, days: 3,
    season: "Mar - May, Oct - Dec", seasons: ["Spring", "Autumn"], price: 8500,
    lat: 27.2, lon: 88.12, base: "Okhrey", wild: "forest", tags: ["light"], fit: 1,
    desc: "In April this sanctuary simply <strong>catches fire in pink and red</strong> — a gentle ridge amble through one of the world's great rhododendron forests, Kanchenjunga peeking over the blooms.",
    hl: ["600 hectares of rhododendron", "April superbloom", "Kanchenjunga over the blooms", "Village homestays", "Genuinely easy"],
    cps: [["Okhrey", "8,530 ft", "Sherpa village trailhead.", ["Singalila foothills"]],
          ["Barsey", "10,000 ft", "Sanctuary hut in the blooms.", ["Kanchenjunga", "Singalila ridge"]]],
    crux: ["Timing the bloom", "The trek is easy every day of the year; catching peak bloom (mid-April, weather-shifted) is the actual challenge."] },

  { id: "tholung-valley", name: "Tholung Valley", region: "North Sikkim (Dzongu)", state: "Sikkim",
    diff: "Moderate", scene: "forest", ft: "12,894 ft", m: 3930, km: 40, days: 6,
    season: "Mar - May, Oct - Nov", seasons: ["Spring", "Autumn"], price: 18500,
    lat: 27.55, lon: 88.5, base: "Lingthem (Dzongu)", wild: "forest", tags: ["pilgrim"], fit: 3,
    desc: "Into <strong>Dzongu, the Lepcha holy land</strong> — waterfalls at every bend, the 18th-century Tholung monastery, and cardamom forests that end beneath glacier walls.",
    hl: ["Lepcha reserve access", "Tholung monastery relics", "Waterfall alley", "Cardamom jungles", "Deep cultural trek"],
    cps: [["Lingthem", "5,250 ft", "Dzongu permit village.", ["Teesta confluences"]],
          ["Tholung Gompa", "8,070 ft", "The treasure monastery.", ["Forested walls"]],
          ["Kishong Valley", "12,894 ft", "Alpine head of the valley.", ["Lama Angden", "Siniolchu (far)"]]],
    crux: ["Leech kilometres in the cardamom belt", "Between 5,000–8,000 ft the forest is leech republic in any damp month — salt socks and stoicism."] },

  { id: "phoktey-dara", name: "Phoktey Dara (Uttarey Singalila)", region: "West Sikkim", state: "Sikkim",
    diff: "Moderate", scene: "sunset", ft: "13,222 ft", m: 4030, km: 35, days: 5,
    season: "Mar - May, Oct - Dec", seasons: ["Spring", "Autumn"], price: 13500,
    lat: 27.27, lon: 88.05, base: "Uttarey", wild: "forest", tags: [], fit: 3,
    desc: "The Singalila ridge's Sikkim-side secret — Sandakphu's panorama <strong>without Sandakphu's jeeps</strong>, from a summit that stares down the whole border ridge.",
    hl: ["Sandakphu views, zero vehicles", "Singalila ridge from Sikkim", "Old trade-route forests", "Homestay culture", "April magnolias"],
    cps: [["Uttarey", "6,600 ft", "Border village trailhead.", ["Singalila forests"]],
          ["Chiwabhanjang", "10,170 ft", "Pass camp on the border ridge.", ["Ridge into Nepal"]],
          ["Phoktey Dara", "13,222 ft", "The summit grandstand.", ["Kanchenjunga family", "Everest cluster (far)", "Chomolhari (far)"]]],
    crux: ["Ridge cold snaps", "Between October and April the border ridge swings 20 °C in an hour when cloud rolls in — summit early, descend earlier."] },

  { id: "tonglu-tumling", name: "Tonglu – Tumling Weekend", region: "Darjeeling", state: "West Bengal",
    diff: "Easy", scene: "forest", ft: "10,130 ft", m: 3088, km: 24, days: 3,
    season: "Oct - Apr", seasons: ["Autumn", "Winter", "Spring"], price: 6500,
    lat: 27.03, lon: 88.08, base: "Manebhanjan", wild: "forest", tags: ["light"], fit: 1,
    desc: "The Sleeping Buddha on a weekend — two gentle days up the Singalila flank to teahouses where <strong>Kanchenjunga fills your breakfast window</strong>.",
    hl: ["Kanchenjunga breakfast views", "True weekend trek", "Nepal-India teahouses", "Winter snow mornings", "First-trek friendly"],
    cps: [["Manebhanjan", "6,325 ft", "Shared start with Sandakphu.", ["Foothills"]],
          ["Tonglu", "10,130 ft", "Trekkers' hut summit.", ["Kanchenjunga", "Sleeping Buddha line"]],
          ["Tumling", "9,600 ft", "Homely ridge hamlet.", ["Kanchenjunga panorama"]]],
    crux: ["None, honestly", "The steepest thing here is the teahouse ladder — this is the trek to bring parents on."] },

  /* ================= HIMACHAL (15) ================= */
  { id: "patalsu-peak", name: "Patalsu Peak", region: "Kullu (Solang)", state: "Himachal Pradesh",
    diff: "Moderate", scene: "winter", ft: "13,845 ft", m: 4220, km: 18, days: 3,
    season: "Mar - Jun, Oct - Dec", seasons: ["Spring", "Summer", "Autumn", "Winter"], price: 8500,
    lat: 32.32, lon: 77.15, base: "Solang Valley", wild: "forest", tags: ["snow"], fit: 3,
    desc: "Solang's own summit — a proper 4,220 m top in three days, with <strong>Hanuman Tibba filling the sky</strong> and paragliders drifting far below your boots.",
    hl: ["Real summit in 3 days", "Hanuman Tibba face view", "Winter climb option", "Manali doorstep", "Big reward:effort ratio"],
    cps: [["Solang", "8,400 ft", "Adventure valley base.", ["Friendship Peak"]],
          ["Shagadugh", "10,800 ft", "Meadow camp in the forest gap.", ["Solang valley below"]],
          ["Patalsu Summit", "13,845 ft", "Ridge-top over everything.", ["Hanuman Tibba", "Friendship Peak", "Seven Sisters", "Deo Tibba (far)"]]],
    crux: ["Summit ridge cornices (winter–spring)", "December–April the final ridge grows wind-slab and cornice — rope up or settle for the shoulder."] },

  { id: "yulla-kanda", name: "Yulla Kanda", region: "Kinnaur", state: "Himachal Pradesh",
    diff: "Moderate", scene: "lakes", ft: "12,887 ft", m: 3928, km: 16, days: 3,
    season: "May - Oct", seasons: ["Summer", "Monsoon", "Autumn"], price: 7500,
    lat: 31.62, lon: 78.11, base: "Yulla Khas (Kinnaur)", wild: "meadow", tags: ["pilgrim"], fit: 3,
    desc: "Home of the <strong>world's highest Krishna temple</strong>, on an island in a heart-shaped lake — Kinnaur's Janmashtami pilgrimage doubles as a superb short trek.",
    hl: ["Highest Krishna temple", "Heart-shaped lake", "Janmashtami fair", "Kinnaur apple villages", "Short but high"],
    cps: [["Yulla Khas", "8,860 ft", "Apple-orchard village.", ["Sutlej gorge"]],
          ["Gufa Camp", "11,150 ft", "Forest cave camp.", ["Kinner Kailash glimpses"]],
          ["Yulla Kanda", "12,887 ft", "The lake and its island temple.", ["Kinner Kailash range", "Sutlej valley depths"]]],
    crux: ["Sustained gradient from the village", "4,000 ft in barely 8 km — short never meant flat in Kinnaur."] },

  { id: "lamkhaga-pass", name: "Lamkhaga Pass", region: "Kinnaur-Uttarkashi", state: "Himachal Pradesh",
    diff: "Expedition", scene: "glacier", ft: "17,336 ft", m: 5284, km: 70, days: 9,
    season: "Jun, Sep", seasons: ["Summer", "Autumn"], price: 38500,
    lat: 31.35, lon: 78.44, base: "Chitkul", wild: "glacier", tags: ["rope", "glacier"], fit: 5,
    desc: "The great Kinnaur–Garhwal connector — from India's 'last village' Chitkul over a <strong>crevassed 5,284 m pass</strong> to the Bhagirathi valley at Harsil. Serious, historic, sublime.",
    hl: ["Chitkul to Harsil crossing", "Crevassed pass glacier", "Baspa valley wilderness", "Two-state traverse", "Mountaineer's trek"],
    cps: [["Chitkul", "11,320 ft", "India's last Baspa village.", ["Baspa headwalls"]],
          ["Ranikanda", "13,120 ft", "Meadow camp up-valley.", ["Baspa glacier ranges"]],
          ["Gundar", "14,760 ft", "Boulder camp before the ice.", ["Lamkhaga ramparts"]],
          ["Lamkhaga Pass", "17,336 ft", "The crossing.", ["Baspa peaks behind", "Gangotri ranges ahead"]],
          ["Harsil", "8,530 ft", "Deodar paradise on the Bhagirathi.", ["Srikanth", "Bandarpoonch (far)"]]],
    crux: ["The crevasse field below the pass", "Both flanks carry open slots by late season — teams rope the top kilometre in all conditions."] },

  { id: "borasu-pass", name: "Borasu Pass", region: "Uttarkashi-Kinnaur", state: "Himachal Pradesh",
    diff: "Hard", scene: "glacier", ft: "17,880 ft", m: 5450, km: 55, days: 8,
    season: "Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 26500,
    lat: 31.24, lon: 78.35, base: "Sankri → Chitkul", wild: "alpine", tags: ["snow", "glacier"], fit: 5,
    desc: "Har Ki Dun's wild exit — instead of walking back, climb out of the valley of gods over <strong>Borasu's snow ramparts</strong> and descend to Chitkul in Kinnaur.",
    hl: ["Har Ki Dun → Kinnaur crossover", "17,880 ft snow pass", "Two iconic valleys linked", "Very few takers", "Big-mountain atmosphere"],
    cps: [["Sankri", "6,400 ft", "Garhwal-side start.", ["Tons valley"]],
          ["Har Ki Dun", "11,675 ft", "Valley of gods junction.", ["Swargarohini"]],
          ["Upper Lamjung", "14,760 ft", "Glacial rubble camp.", ["Borasu wall"]],
          ["Borasu Pass", "17,880 ft", "Snow saddle between worlds.", ["Swargarohini", "Kinner Kailash range ahead", "Baspa valley below"]],
          ["Chitkul", "11,320 ft", "Kinnaur's last village.", ["Baspa valley"]]],
    crux: ["Twin bergschrunds at the top", "The final 200 m weaves between two gaping schrunds on 40° snow — early-season snow bridges or late-season ladder-work."] },

  { id: "kugti-pass", name: "Kugti Pass", region: "Chamba (Bharmour)", state: "Himachal Pradesh",
    diff: "Hard", scene: "alpine", ft: "16,600 ft", m: 5060, km: 60, days: 8,
    season: "Jun - Jul, Sep", seasons: ["Summer", "Autumn"], price: 22500,
    lat: 32.35, lon: 76.68, base: "Bharmour", wild: "alpine", tags: ["snow"], fit: 4,
    desc: "The Gaddi shepherds' highway over the Pir Panjal — from Bharmour's ancient temples past <strong>Mani Mahesh Kailash</strong> into Lahaul, walking a migration older than maps.",
    hl: ["Gaddi migration route", "Mani Mahesh Kailash views", "Chamba temple culture", "Chamba→Lahaul crossing", "Wool-trail history"],
    cps: [["Bharmour", "7,000 ft", "84-temple chaurasi town.", ["Budhil valley"]],
          ["Kugti Village", "8,530 ft", "Last village, wood-carved homes.", ["Kailash glimpses"]],
          ["Duggi", "12,140 ft", "Shepherd meadow camp.", ["Mani Mahesh Kailash"]],
          ["Kugti Pass", "16,600 ft", "The Pir Panjal crossing.", ["Mani Mahesh Kailash", "Lahaul's brown ranges ahead"]]],
    crux: ["The scree couloir below the pass", "800 ft of moving stone where shepherds send sheep first — follow their line exactly."] },

  { id: "manimahesh-kailash", name: "Manimahesh Kailash Yatra", region: "Chamba (Bharmour)", state: "Himachal Pradesh",
    diff: "Moderate", scene: "lakes", ft: "13,006 ft", m: 3964, km: 26, days: 3,
    season: "Jun - Oct (yatra Aug-Sep)", seasons: ["Summer", "Monsoon", "Autumn"], price: 7999,
    lat: 32.4, lon: 76.66, base: "Hadsar (Bharmour)", wild: "meadow", tags: ["pilgrim"], fit: 3,
    desc: "To the lake beneath <strong>Shiva's Kailash of Chamba</strong> — the 5,653 m peak no one has (rightly) climbed, mirrored in the waters where lakhs of pilgrims dip each Janmashtami.",
    hl: ["Mani Mahesh Kailash face", "Sacred mirror lake", "Great yatra energy", "Short & intense", "Chamba culture"],
    cps: [["Hadsar", "6,900 ft", "Yatra trailhead.", ["Budhil gorge"]],
          ["Dhancho", "9,190 ft", "Waterfall camp.", ["Kailash glimpse"]],
          ["Manimahesh Lake", "13,006 ft", "The mirror of Kailash.", ["Mani Mahesh Kailash", "its hanging glacier"]]],
    crux: ["Yatra-season crowds vs off-season ice", "Choose your difficulty: lakhs of pilgrims in September, or icy solitude in June and October."] },

  { id: "miyar-valley", name: "Miyar Valley", region: "Lahaul", state: "Himachal Pradesh",
    diff: "Moderate", scene: "valley", ft: "12,800 ft", m: 3901, km: 60, days: 8,
    season: "Jun - Sep", seasons: ["Summer", "Monsoon"], price: 24500,
    lat: 32.75, lon: 76.85, base: "Udaipur (Lahaul)", wild: "spiti", tags: [], fit: 3,
    desc: "'The valley of flowers of Lahaul' — twelve glacial side-valleys, granite walls that draw the world's climbers, and <strong>Menthosa</strong> presiding over blue-sheep meadows.",
    hl: ["Granite big-walls", "Menthosa views", "Flower meadows in a desert", "Blue-sheep country", "Expedition gateway"],
    cps: [["Udaipur", "8,660 ft", "Lahaul market town.", ["Miyar nallah mouth"]],
          ["Shukto", "10,500 ft", "Village of the upper valley.", ["Granite spires begin"]],
          ["Yolthang", "11,800 ft", "The great flower meadow.", ["Menthosa", "castle walls"]],
          ["Miyar Glacier Snout", "12,800 ft", "End of the green.", ["Menthosa", "Miyar granite towers"]]],
    crux: ["River braids in afternoon melt", "Multiple glacier-fed crossings that double by 2 PM — Miyar days are morning days."] },

  { id: "chandratal-baralacha", name: "Chandratal – Baralacha La", region: "Lahaul-Spiti", state: "Himachal Pradesh",
    diff: "Moderate", scene: "lakes", ft: "16,040 ft", m: 4890, km: 45, days: 6,
    season: "Jul - Sep", seasons: ["Monsoon", "Summer"], price: 18500,
    lat: 32.48, lon: 77.62, base: "Batal", wild: "spiti", tags: [], fit: 4,
    desc: "From the <strong>moon lake</strong> along the old Spiti–Ladakh caravan line to Baralacha La — high-desert trekking where every camp sits above 4,200 m.",
    hl: ["Chandratal's colour shifts", "Caravan-route history", "Suraj Tal finish", "All-high itinerary", "Star fields at night"],
    cps: [["Batal", "13,000 ft", "Dhaba junction on the Spiti road.", ["CB range walls"]],
          ["Chandratal", "14,100 ft", "The crescent moon lake.", ["CB-13 & CB-14", "Mulkila (far)"]],
          ["Tokpo Yongma", "15,400 ft", "River camp one.", ["Lahaul brown giants"]],
          ["Baralacha La", "16,040 ft", "Triple-watershed pass.", ["Mulkila", "Suraj Tal below"]]],
    crux: ["Ice-melt river crossings", "Tokpo Yongma and Gongma cross thigh-deep glacier rivers — dawn starts, linked arms, sandals in hand."] },

  { id: "tosh-kutla", name: "Tosh & Kutla", region: "Kullu (Parvati)", state: "Himachal Pradesh",
    diff: "Easy", scene: "forest", ft: "9,842 ft", m: 3000, km: 12, days: 2,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Monsoon", "Autumn"], price: 3950,
    lat: 32.05, lon: 77.45, base: "Tosh", wild: "forest", tags: ["light"], fit: 1,
    desc: "Above the Parvati café-trail lies <strong>Kutla — a hanging meadow under Papsura's 'peak of evil'</strong> — proof that one easy hour can change an entire valley's mood.",
    hl: ["Kutla's hidden bowl", "Papsura & Dharamsura views", "Café-to-wilderness in 1 hr", "Snow-play winters", "Perfect chill trek"],
    cps: [["Tosh", "7,870 ft", "Village at the valley's end.", ["Parvati walls"]],
          ["Kutla", "9,842 ft", "The hanging meadow.", ["Papsura", "Dharamsura (White Sail)"]]],
    crux: ["Mud season slicks", "The one climb gets slick as soap in melt or rain — trail shoes over sneakers, always."] },

  { id: "rashol-pass", name: "Rashol Pass", region: "Kullu (Parvati)", state: "Himachal Pradesh",
    diff: "Moderate", scene: "forest", ft: "10,463 ft", m: 3189, km: 20, days: 3,
    season: "Apr - Jun, Sep - Nov", seasons: ["Spring", "Summer", "Autumn"], price: 5500,
    lat: 32.03, lon: 77.36, base: "Kasol", wild: "forest", tags: [], fit: 3,
    desc: "The forest bridge between the Parvati and Malana worlds — a deodar tunnel climb to a notch with <strong>both valleys at your feet</strong>.",
    hl: ["Kasol → Malana crossing", "Deodar forest tunnel", "Two-valley viewpoint", "Village-to-village trek", "Low season friendly"],
    cps: [["Kasol", "5,200 ft", "Parvati base town.", ["Valley pines"]],
          ["Rashol Village", "7,870 ft", "Stone-and-wood hill village.", ["Parvati depths"]],
          ["Rashol Pass", "10,463 ft", "The forest notch.", ["Chanderkhani ridge", "Malana valley", "Parvati valley"]]],
    crux: ["Relentless forest staircase", "No views, no mercy till the top — the pass pays it all back at once."] },

  { id: "bijli-mahadev", name: "Bijli Mahadev", region: "Kullu", state: "Himachal Pradesh",
    diff: "Easy", scene: "forest", ft: "8,091 ft", m: 2466, km: 8, days: 1,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Monsoon", "Autumn"], price: 2450,
    lat: 31.94, lon: 77.17, base: "Chansari (Kullu)", wild: "forest", tags: ["light", "pilgrim"], fit: 1,
    desc: "The temple of the <strong>lightning Shiva</strong> — its lingam is shattered by strikes and rejoined with butter — on a grass top with the Kullu and Parvati valleys unrolled below.",
    hl: ["Lightning-temple legend", "Kullu valley panorama", "Half-day classic", "Grass-ridge picnics", "Great first hike"],
    cps: [["Chansari", "6,230 ft", "Steps-start village.", ["Kullu valley"]],
          ["Bijli Mahadev", "8,091 ft", "The lightning temple ridge.", ["Pir Panjal wall", "Parvati confluence below"]]],
    crux: ["Just the stairs", "A thousand-odd stone steps — pace them and the ridge is pure reward."] },

  { id: "hatu-peak", name: "Hatu Peak (Narkanda)", region: "Shimla", state: "Himachal Pradesh",
    diff: "Easy", scene: "winter", ft: "11,152 ft", m: 3399, km: 10, days: 2,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Autumn"], price: 3450,
    lat: 31.25, lon: 77.45, base: "Narkanda", wild: "forest", tags: ["light"], fit: 1,
    desc: "Shimla district's rooftop — a cedar-forest stroll to the carved <strong>Hatu Mata temple</strong>, with the whole snowline from Srikhand to Kinnaur across the horizon.",
    hl: ["Snowline panorama", "Carved wooden temple", "Narkanda ski slopes", "Apple-country drives", "Winter snowshoe option"],
    cps: [["Narkanda", "8,850 ft", "Highway ridge town.", ["Orchards & cedars"]],
          ["Hatu Peak", "11,152 ft", "Temple summit.", ["Srikhand ridge", "Kinner Kailash range (far)", "Chanshal (far)"]]],
    crux: ["Ice on the road-trail (Dec–Mar)", "The jeep track shortcuts glaze over in winter shade — light spikes make it a joy."] },

  { id: "dainkund-khajjiar", name: "Dainkund – Khajjiar", region: "Chamba (Dalhousie)", state: "Himachal Pradesh",
    diff: "Easy", scene: "meadow", ft: "9,022 ft", m: 2750, km: 10, days: 2,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Monsoon", "Autumn"], price: 3950,
    lat: 32.53, lon: 76.0, base: "Dalhousie", wild: "forest", tags: ["light"], fit: 1,
    desc: "The 'singing hill' to <strong>'mini Switzerland'</strong> — a whistling-wind ridge walk from Dainkund's air-force top down to Khajjiar's lake-in-a-meadow.",
    hl: ["Khajjiar meadow lake", "Whistling ridge winds", "Pir Panjal views", "Deodar cathedral", "Family favourite"],
    cps: [["Dainkund", "9,022 ft", "The singing hill.", ["Pir Panjal line", "Mani Mahesh (far)"]],
          ["Khajjiar", "6,500 ft", "Mini Switzerland bowl.", ["Meadow rim deodars"]]],
    crux: ["Choosing a clear day", "Nothing is hard — but haze steals the Pir Panjal wall; go post-rain or in winter light."] },

  { id: "chanshal-pass", name: "Chanshal Pass Meadows", region: "Shimla (Rohru)", state: "Himachal Pradesh",
    diff: "Moderate", scene: "meadow", ft: "14,830 ft", m: 4520, km: 30, days: 4,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 12500,
    lat: 31.2, lon: 77.98, base: "Rohru", wild: "meadow", tags: [], fit: 3,
    desc: "Above the Pabbar's apple country, <strong>Chanshal's meadow crest</strong> runs for kilometres at 4,000+ m — Buran Ghati's views without Buran Ghati's queue.",
    hl: ["Km-long meadow crest", "Apple-valley base", "Kinnaur wall views", "Snowfields till June", "Quiet alternative"],
    cps: [["Rohru", "5,100 ft", "Pabbar valley market town.", ["Apple terraces"]],
          ["Larot", "9,190 ft", "Roadhead hamlet.", ["Chanshal forests"]],
          ["Chanshal Pass", "14,830 ft", "The great grass crest.", ["Kinner Kailash range", "Pabbar valley", "Dhauladhar (far)"]]],
    crux: ["Exposure to weather, not terrain", "The crest has zero shelter for hours — thunder-cell afternoons demand alpine-style early turnarounds."] },

  { id: "minkiani-pass", name: "Minkiani Pass (Dhauladhar)", region: "Kangra", state: "Himachal Pradesh",
    diff: "Hard", scene: "alpine", ft: "13,779 ft", m: 4200, km: 36, days: 5,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 12500,
    lat: 32.25, lon: 76.25, base: "Kareri Village", wild: "alpine", tags: ["snow"], fit: 4,
    desc: "Kareri Lake's serious sequel — over the <strong>Dhauladhar crest</strong> at Minkiani into the Chamba lakes bowl, the shepherds' shortcut between two worlds.",
    hl: ["Dhauladhar crest crossing", "Lam Dal sacred lakes", "Kareri Lake en route", "Gaddi shortcut route", "Fierce & compact"],
    cps: [["Kareri Village", "5,900 ft", "Slate-roof trailhead.", ["Dhauladhar wall"]],
          ["Kareri Lake", "9,650 ft", "The clearwater base.", ["Minkiani ridge"]],
          ["Minkiani Pass", "13,779 ft", "Notch in the granite crest.", ["Mon (Moon Peak)", "Lam Dal below", "Chamba ranges"]],
          ["Lam Dal", "12,140 ft", "Largest of the seven sacred lakes.", ["Dhauladhar backside"]]],
    crux: ["Boulder ramp to the notch", "The last 1,500 ft is granite blocks at 40° that hold snow till mid-June — axe confidence required."] },

  /* ================= UTTARAKHAND (15) ================= */
  { id: "vasuki-tal-kedarnath", name: "Vasuki Tal (Kedarnath)", region: "Rudraprayag", state: "Uttarakhand",
    diff: "Hard", scene: "lakes", ft: "14,200 ft", m: 4328, km: 16, days: 4,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 9500,
    lat: 30.73, lon: 79.07, base: "Kedarnath", wild: "alpine", tags: ["pilgrim"], fit: 4,
    desc: "Above the great shrine, a brutal little climb to the tarn where <strong>Vasuki the serpent rests</strong> — Chaukhamba floating in the water when dawn behaves.",
    hl: ["Chaukhamba reflections", "Kedarnath shrine base", "Short & steep", "Brahma kamal meadows", "Yatra + trek combo"],
    cps: [["Kedarnath", "11,755 ft", "The great Shiva shrine.", ["Kedarnath dome", "Bharatekuntha"]],
          ["Vasuki Top", "14,200 ft", "Ridge above the tarn.", ["Chaukhamba", "Kedar dome", "Vasuki Tal below"]]],
    crux: ["4,000 ft of no-nonsense ridge", "Straight up from the temple with zero warm-up — most who struggle came straight from the helicopter."] },

  { id: "khatling-glacier", name: "Khatling Glacier", region: "Tehri", state: "Uttarakhand",
    diff: "Hard", scene: "glacier", ft: "12,195 ft", m: 3717, km: 48, days: 7,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 13500,
    lat: 30.53, lon: 78.75, base: "Ghuttu", wild: "alpine", tags: [], fit: 4,
    desc: "The Bhilangana's wild source — a shepherd trail past waterfalls to the <strong>Khatling snout under Thalay Sagar's spear</strong>, on the forgotten side of the Gangotri giants.",
    hl: ["Thalay Sagar's south side", "Bhilangana gorge trail", "Zero-crowd glacier", "Waterfall alley", "Old expedition route"],
    cps: [["Ghuttu", "4,920 ft", "Roadhead bazaar.", ["Bhilangana valley"]],
          ["Gangi", "8,530 ft", "The last, oldest village.", ["Valley narrows"]],
          ["Bhumka", "10,500 ft", "Forest-line camp.", ["Khatling walls"]],
          ["Khatling Snout", "12,195 ft", "The glacier's black mouth.", ["Thalay Sagar", "Jogin group", "Kirti Stambh"]]],
    crux: ["Washed-out gorge sections", "Every monsoon rewrites the trail past Gangi — expect ladders, log bridges and improvisation."] },

  { id: "mayali-pass", name: "Mayali Pass Traverse", region: "Tehri-Rudraprayag", state: "Uttarakhand",
    diff: "Expedition", scene: "glacier", ft: "16,400 ft", m: 5000, km: 70, days: 9,
    season: "Jun, Sep", seasons: ["Summer", "Autumn"], price: 24500,
    lat: 30.6, lon: 78.9, base: "Ghuttu → Kedarnath", wild: "glacier", tags: ["rope", "glacier"], fit: 5,
    desc: "Khatling to Kedarnath over <strong>Mayali's snow saddle</strong> — the pilgrim-mountaineer's line linking the Bhilangana wilderness to the great shrine, glacier lakes en route.",
    hl: ["Wilderness-to-shrine traverse", "Masar Tal & Vasuki Tal", "Glacier pass crossing", "Ends at Kedarnath arati", "Rare and committing"],
    cps: [["Ghuttu", "4,920 ft", "Bhilangana start.", ["Valley forests"]],
          ["Khatling moraine", "12,195 ft", "Below the icefalls.", ["Thalay Sagar", "Jogin"]],
          ["Masar Tal", "13,780 ft", "Blue tarn camp.", ["Thalay Sagar close"]],
          ["Mayali Pass", "16,400 ft", "The snow saddle.", ["Chaukhamba", "Kedar dome", "Jogin group"]],
          ["Kedarnath", "11,755 ft", "Descend to the shrine.", ["Kedarnath dome"]]],
    crux: ["Pass day across two glacier shelves", "Roped travel over crevassed ramps both sides of the saddle — a mountaineering day inside a trek."] },

  { id: "chenap-valley", name: "Chenap Valley", region: "Chamoli", state: "Uttarakhand",
    diff: "Moderate", scene: "floral", ft: "13,120 ft", m: 4000, km: 36, days: 6,
    season: "Jul - Sep", seasons: ["Monsoon"], price: 12500,
    lat: 30.6, lon: 79.5, base: "Thaing (Joshimath)", wild: "meadow", tags: ["monsoon"], fit: 3,
    desc: "The <strong>'new Valley of Flowers'</strong> the shepherds always knew — seven flower-flooded meadows on Dronagiri's flank, still without a ticket counter.",
    hl: ["Flower carpets sans crowds", "Seven linked meadows", "Dronagiri backdrop", "Village homestay start", "Monsoon speciality"],
    cps: [["Thaing", "7,200 ft", "Roadhead village near Joshimath.", ["Dhauli valley"]],
          ["Dumak", "9,850 ft", "Remote village of honey and wool.", ["Forest ridges"]],
          ["Chenap Meadows", "13,120 ft", "The flower seas.", ["Dronagiri", "Hathi-Ghoda", "Nilkantha (far)"]]],
    crux: ["Leech belt & landslide bends", "Monsoon gives the flowers and takes the trail — gaiters, salt and flexible days."] },

  { id: "kedarnath-trek", name: "Kedarnath Yatra Trek", region: "Rudraprayag", state: "Uttarakhand",
    diff: "Moderate", scene: "alpine", ft: "11,755 ft", m: 3583, km: 18, days: 2,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 5500,
    lat: 30.74, lon: 79.07, base: "Gaurikund", wild: "forest", tags: ["pilgrim"], fit: 3,
    desc: "The rebuilt great yatra — 16 km of graded pilgrim path up the Mandakini to the <strong>thousand-year shrine beneath Kedarnath dome</strong>, walked by monks and grandmothers alike.",
    hl: ["The great Shiva shrine", "Rebuilt post-2013 path", "Mandakini gorge", "Arati at altitude", "Accessible challenge"],
    cps: [["Gaurikund", "6,500 ft", "Hot-spring trailhead.", ["Mandakini gorge"]],
          ["Bhimbali", "8,530 ft", "Midway rest complex.", ["Gorge waterfalls"]],
          ["Kedarnath", "11,755 ft", "The shrine and its dome.", ["Kedarnath dome", "Bharatekuntha"]]],
    crux: ["Altitude on a crowd schedule", "The path is engineered; the 5,000 ft gain isn't — pilgrims who stride with the mules pay above Bhimbali."] },

  { id: "kush-kalyan", name: "Kush Kalyan Bugyal", region: "Tehri", state: "Uttarakhand",
    diff: "Easy", scene: "meadow", ft: "11,155 ft", m: 3400, km: 28, days: 4,
    season: "Apr - Jun, Sep - Nov", seasons: ["Spring", "Summer", "Autumn"], price: 8500,
    lat: 30.73, lon: 78.6, base: "Silla Village", wild: "meadow", tags: [], fit: 2,
    desc: "One of Asia's largest high meadows, minus Sahastra Tal's grind — <strong>a grass ocean</strong> where Gujjar buffalo herds drift beneath the Gangotri skyline.",
    hl: ["Vast meadow plateau", "Buffalo-herder culture", "Gangotri range skyline", "Gentle gradients up top", "Sahastra Tal's easy half"],
    cps: [["Silla", "6,300 ft", "Bhilangana roadhead.", ["Valley ridges"]],
          ["Pinswad", "8,200 ft", "Village below the shelf.", ["Forest bands"]],
          ["Kush Kalyan", "11,155 ft", "The grass ocean.", ["Jaonli", "Draupadi ka Danda", "Gangotri range"]]],
    crux: ["The shelf climb from Pinswad", "One honest 3,000 ft forest day buys three days of flat heaven."] },

  { id: "binsar-zero-point", name: "Binsar Zero Point", region: "Almora", state: "Uttarakhand",
    diff: "Easy", scene: "forest", ft: "7,913 ft", m: 2412, km: 10, days: 2,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Autumn"], price: 3450,
    lat: 29.7, lon: 79.75, base: "Binsar Sanctuary Gate", wild: "forest", tags: ["light"], fit: 1,
    desc: "An oak-forest amble to the tower where <strong>300 km of Himalaya</strong> stands on parade — Kedarnath to Panchachuli in one slow, astonished pan.",
    hl: ["300 km snow panorama", "Leopard-forest sanctuary", "Colonial-era estates", "Birding paradise", "Zero fitness bar"],
    cps: [["Binsar Gate", "7,000 ft", "Sanctuary entrance.", ["Oak canopy"]],
          ["Zero Point", "7,913 ft", "The panorama tower.", ["Nanda Devi", "Trishul", "Panchachuli", "Kedarnath (far)"]]],
    crux: ["Morning haze management", "The walk never tests you; the view demands a pre-9 AM arrival October–March."] },

  { id: "khaliya-top", name: "Khaliya Top (Munsiyari)", region: "Pithoragarh", state: "Uttarakhand",
    diff: "Easy", scene: "meadow", ft: "11,500 ft", m: 3505, km: 16, days: 3,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Autumn"], price: 6500,
    lat: 30.06, lon: 80.2, base: "Munsiyari", wild: "meadow", tags: ["snow"], fit: 2,
    desc: "Munsiyari's balcony meadow — two easy days to a ridge where the <strong>Panchachuli wall fills half the world</strong>, snowshoe-friendly all winter.",
    hl: ["Panchachuli in your face", "Winter snow-trek option", "KMVN hut stay", "Rhododendrons in March", "Big view, small effort"],
    cps: [["Munsiyari", "7,200 ft", "The Panchachuli balcony town.", ["Panchachuli I–V"]],
          ["Khaliya Base", "9,500 ft", "Forest hut clearing.", ["Peaks through pines"]],
          ["Khaliya Top", "11,500 ft", "The meadow crown.", ["Panchachuli I–V", "Rajrambha", "Nanda Devi East (far)"]]],
    crux: ["Winter ice crust", "December–February the meadow crusts hard; microspikes turn a slip-fest into the best snow walk in Kumaon."] },

  { id: "adi-kailash", name: "Adi Kailash & Om Parvat", region: "Pithoragarh (Vyas)", state: "Uttarakhand",
    diff: "Moderate", scene: "alpine", ft: "14,764 ft", m: 4500, km: 70, days: 8,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 28500,
    lat: 30.15, lon: 80.85, base: "Dharchula", wild: "spiti", tags: ["pilgrim"], fit: 3,
    desc: "The inner-line pilgrimage to <strong>Shiva's other Kailash</strong> and the mountain where snow spells <strong>ॐ</strong> — Vyas valley villages, Kali gorge roads and Tibet-border silence.",
    hl: ["Om Parvat's snow ॐ", "Adi Kailash darshan", "Inner-line permits", "Kuti — Pandava village", "Border-land culture"],
    cps: [["Dharchula", "3,050 ft", "Permit town on the Kali.", ["Kali gorge"]],
          ["Gunji", "10,370 ft", "Vyas valley hub village.", ["Api (Nepal) glimpse"]],
          ["Kuti", "12,140 ft", "Village of the Pandavas.", ["Adi Kailash first view"]],
          ["Jolingkong Lake", "14,764 ft", "Beneath the holy pyramid.", ["Adi Kailash", "Brahma Parvat"]],
          ["Om Parvat View", "14,000 ft", "The ॐ written in snow.", ["Om Parvat", "Kali headwaters"]]],
    crux: ["Permits & gorge roads, not gradient", "The walking is moderate; inner-line paperwork and monsoon-cut roads are the true gatekeepers."] },

  { id: "ranthan-kharak", name: "Ranthan Kharak", region: "Bageshwar", state: "Uttarakhand",
    diff: "Moderate", scene: "meadow", ft: "12,500 ft", m: 3810, km: 30, days: 5,
    season: "Mar - Jun, Sep - Dec", seasons: ["Spring", "Summer", "Autumn", "Winter"], price: 11500,
    lat: 30.05, lon: 79.9, base: "Gogina (Bageshwar)", wild: "meadow", tags: ["snow"], fit: 3,
    desc: "Kumaon's breakout star — a herders' ridge camp with <strong>Nanda Devi, Nanda Kot and Panchachuli</strong> arranged like a private screening, still uncrowded.",
    hl: ["Front-row Nanda Devi views", "New-classic status", "Herder kharak camps", "Winter snow-ridge option", "Village trail charm"],
    cps: [["Gogina", "5,900 ft", "Remote roadhead village.", ["Saryu valley"]],
          ["Namik", "8,200 ft", "Glacier-famous village.", ["Forest ridges"]],
          ["Ranthan Kharak", "12,500 ft", "The grandstand ridge camp.", ["Nanda Devi", "Nanda Kot", "Panchachuli", "Nanda Khat"]]],
    crux: ["Ridge weather roulette", "The camp's glory is its exposure — when fronts cross Kumaon, this ridge feels them first."] },

  { id: "dev-kyara", name: "Dev Kyara (Obra Valley)", region: "Uttarkashi", state: "Uttarakhand",
    diff: "Moderate", scene: "valley", ft: "12,795 ft", m: 3900, km: 40, days: 6,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 13500,
    lat: 31.1, lon: 78.15, base: "Jakhol (Mori)", wild: "meadow", tags: [], fit: 3,
    desc: "The Obra valley's <strong>'meadow of the gods'</strong> — waterfalls stacked on waterfalls beneath Ranglana's fang, on the newest permit-trail out of the Tons.",
    hl: ["Ranglana's rock fang", "Stacked waterfalls", "Newly opened route", "Tons valley culture", "Supin-side scenery"],
    cps: [["Jakhol", "6,700 ft", "Supin valley trailhead.", ["Tons forests"]],
          ["Bhawa", "9,200 ft", "Shepherd clearing camp.", ["Obra gorge"]],
          ["Dev Kyara", "12,795 ft", "The god-meadow bowl.", ["Ranglana", "Dev Kyara icefalls", "Swargarohini (far)"]]],
    crux: ["Obra's slick log bridges", "The gorge crossings are shepherd-grade — wet logs over loud water, twice daily."] },

  { id: "ali-bedni-bugyal", name: "Ali – Bedni Bugyal", region: "Chamoli", state: "Uttarakhand",
    diff: "Easy", scene: "meadow", ft: "11,500 ft", m: 3505, km: 24, days: 5,
    season: "Mar - Jun, Sep - Dec", seasons: ["Spring", "Summer", "Autumn", "Winter"], price: 8999,
    lat: 30.21, lon: 79.62, base: "Lohajung", wild: "meadow", tags: [], fit: 2,
    desc: "Since Roopkund's camping ban, the meadows became the destination — and honestly, <strong>Asia's finest bugyals with Trishul overhead</strong> never needed the skeletons.",
    hl: ["Asia's finest twin meadows", "Trishul & Nanda Ghunti", "Roopkund's legal half", "Winter snow-meadow option", "Beginner friendly"],
    cps: [["Lohajung", "7,600 ft", "The bugyal basecamp town.", ["Nanda Ghunti glimpse"]],
          ["Didna", "8,045 ft", "Village on the shelf.", ["Neel Ganga forests"]],
          ["Ali Bugyal", "11,320 ft", "The velvet ridge.", ["Trishul", "Nanda Ghunti"]],
          ["Bedni Bugyal", "11,500 ft", "Meadow with the sacred kund.", ["Trishul", "Nanda Ghunti", "Chaukhamba (far)"]]],
    crux: ["Didna's oak staircase", "The one real climb — the same 3,000 ft that guards Roopkund guards its meadows."] },

  { id: "nachiketa-tal", name: "Nachiketa Tal", region: "Uttarkashi", state: "Uttarakhand",
    diff: "Easy", scene: "forest", ft: "8,058 ft", m: 2456, km: 6, days: 1,
    season: "Year-round", seasons: ["Winter", "Spring", "Summer", "Monsoon", "Autumn"], price: 2950,
    lat: 30.66, lon: 78.35, base: "Chaurangi Khal", wild: "forest", tags: ["light", "pilgrim"], fit: 1,
    desc: "The lake of the boy who questioned Death — a <strong>one-day forest pilgrimage</strong> to a leaf-still tarn wrapped in oak and legend, an hour from Uttarkashi.",
    hl: ["Katha-Upanishad legend", "Half-day forest walk", "Temple on the shore", "Uttarkashi add-on", "Monsoon-safe"],
    cps: [["Chaurangi Khal", "6,890 ft", "Roadside trailhead.", ["Oak forest"]],
          ["Nachiketa Tal", "8,058 ft", "The questioning boy's lake.", ["Forest rim — no peaks, all peace"]]],
    crux: ["None — bring a book", "This is the rest-day trek; the only summit is stillness."] },

  { id: "surya-top", name: "Surya Top", region: "Uttarkashi", state: "Uttarakhand",
    diff: "Moderate", scene: "meadow", ft: "13,123 ft", m: 4000, km: 30, days: 5,
    season: "Apr - Jun, Sep - Nov", seasons: ["Spring", "Summer", "Autumn"], price: 11500,
    lat: 30.85, lon: 78.55, base: "Raithal / Barsu", wild: "meadow", tags: ["snow"], fit: 3,
    desc: "Dayara's ambitious sibling — push past the famous meadow to <strong>Surya Top's 360°</strong>, where Srikanth, Bandarpoonch and the Gangotri wall circle the sunrise.",
    hl: ["360° above Dayara", "Gidara-side ridgelines", "Barnala Tal en route", "Fewer crowds up high", "Strong sunrise summit"],
    cps: [["Barsu", "7,380 ft", "Twin trailhead to Raithal.", ["Bhagirathi valley"]],
          ["Barnala Tal", "9,840 ft", "Forest tarn camp.", ["Meadow edges"]],
          ["Dayara Meadows", "11,000 ft", "The classic grass sea.", ["Bandarpoonch", "Black Peak"]],
          ["Surya Top", "13,123 ft", "The sun summit.", ["Srikanth", "Bandarpoonch", "Kala Nag", "Gangotri range", "Jaonli"]]],
    crux: ["The wind ridge above the meadow", "Dayara's crowds vanish exactly where the wind begins — the last 2,000 ft is honest ridge work."] },

  { id: "dronagiri-village", name: "Dronagiri Village Trail", region: "Chamoli (Niti)", state: "Uttarakhand",
    diff: "Moderate", scene: "valley", ft: "11,800 ft", m: 3597, km: 30, days: 5,
    season: "May - Jun, Sep - Oct", seasons: ["Summer", "Autumn"], price: 11999,
    lat: 30.62, lon: 79.72, base: "Jumma (Niti Road)", wild: "alpine", tags: [], fit: 3,
    desc: "To the village that <strong>refuses to worship Hanuman</strong> — he stole their mountain's herb, after all. Living myth on a shelf beneath Dronagiri's 7,000er wall.",
    hl: ["Sanjeevani legend village", "Dronagiri's giant wall", "Niti border-valley culture", "Buckwheat & stone homes", "Gateway to Bagini"],
    cps: [["Jumma", "7,900 ft", "Bridge on the Dhauli Ganga.", ["Gorge walls"]],
          ["Ruing", "9,350 ft", "Forest-shelf hamlet.", ["Dronagiri glimpse"]],
          ["Dronagiri Village", "11,800 ft", "The myth-keeper's village.", ["Dronagiri", "Hathi Parbat", "Bagini valley mouth"]]],
    crux: ["The gorge staircase to Ruing", "Short trek, sharp entry — 1,500 ft of switchbacks straight off the bridge sets the tone."] }
];

expandCompactTreks(T3);
ensureTenOperators();
